#!/bin/ksh

OPENBUS_HOME=/local/openbus/openbus-testes
ACS_PID=$OPENBUS_HOME/data/acs.pid
RGS_PID=$OPENBUS_HOME/data/rgs.pid

# function to check if is running actually
is_running() {
	# if not exist the PID files
	if [ ! -f $ACS_PID ] || [ ! -f $RGS_PID ]; then
		return 1
	else
		# the PID file can be outdated, asking for them
		ps -e |grep $(cat $ACS_PID 2>/dev/null) 1>/dev/null 2>/dev/null
		acs_ret=$?
		ps -e |grep $(cat $RGS_PID 2>/dev/null) 1>/dev/null 2>/dev/null
		rgs_ret=$?
		# if some PID is outdated then remove that file and return false
		running=0
		if [ $acs_ret -gt 0 ]; then
			echo "apaguei"
			rm -f $ACS_PID
			running=1
		fi
		if [ $rgs_ret -gt 0 ]; then
			echo "apaguei"
			rm -f $RGS_PID
			running=1
		fi
		return $running
	fi
	# no problem, all is running
	return 0
}

# check if is running
is_running
ret=$?
# when some error try restart
if [ $ret -gt 0 ] ; then
	# probably the services has crashed!
	# it will try stop any other openbus services
	/etc/init.d/openbus stop

	CRASH_DIR=$OPENBUS_HOME/data/crashes
	TAG=`date +%Y%m%d-%H:%M:%S`
	mkdir -p $CRASH_DIR

	cp $OPENBUS_HOME/data/acs.log $CRASH_DIR/acs-$TAG.log
	cp $OPENBUS_HOME/data/rgs.log $CRASH_DIR/rgs-$TAG.log
	/etc/init.d/openbus start
	echo "Olá,
Sou um notificador automático, que acabou de ver que os serviços do OpenBus na
máquina Ubu/TecGraf falharam!
Acabo de reiniciar os serviços, talvez seja importante você olhar os logs que
foram salvos em:
  $CRASH_DIR/acs-$TAG.log
  $CRASH_DIR/rgs-$TAG.log

Atenciosamente,
Crontab da Máquina Ubu/TecGraf
Autor: Amadeu Barbosa (amadeu@tecgraf.puc-rio.br)" |\
	 mail -s "Falha e reinício do barramento na Ubu/TecGraf" amadeu@tecgraf.puc-rio.br
fi
